name: SHUBUH reminder
on:
  schedule:
    - cron: 31 21 31 5 *
    - cron: 31 21 1 6 *
    - cron: 32 21 2 6 *
    - cron: 32 21 3 6 *
    - cron: 32 21 4 6 *
    - cron: 32 21 5 6 *
    - cron: 32 21 6 6 *
    - cron: 32 21 7 6 *
    - cron: 33 21 8 6 *
    - cron: 33 21 9 6 *
    - cron: 33 21 10 6 *
    - cron: 33 21 11 6 *
    - cron: 33 21 12 6 *
    - cron: 34 21 13 6 *
    - cron: 34 21 14 6 *
    - cron: 34 21 15 6 *
    - cron: 34 21 16 6 *
    - cron: 34 21 17 6 *
    - cron: 35 21 18 6 *
    - cron: 35 21 19 6 *
    - cron: 35 21 20 6 *
    - cron: 35 21 21 6 *
    - cron: 35 21 22 6 *
    - cron: 36 21 23 6 *
    - cron: 36 21 24 6 *
    - cron: 36 21 25 6 *
    - cron: 36 21 26 6 *
    - cron: 37 21 27 6 *
    - cron: 37 21 28 6 *
    - cron: 37 21 29 6 *
env:
  SCHEDULE_NAME: SHUBUH
jobs:
  reminder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Send reminder to slack
        run: echo "Sending $SCHEDULE_NAME reminder to slack"
