name: ISYA reminder
on:
  schedule:
    - cron: 50 11 1 6 *
    - cron: 50 11 2 6 *
    - cron: 51 11 3 6 *
    - cron: 51 11 4 6 *
    - cron: 51 11 5 6 *
    - cron: 51 11 6 6 *
    - cron: 51 11 7 6 *
    - cron: 52 11 8 6 *
    - cron: 52 11 9 6 *
    - cron: 52 11 10 6 *
    - cron: 52 11 11 6 *
    - cron: 52 11 12 6 *
    - cron: 53 11 13 6 *
    - cron: 53 11 14 6 *
    - cron: 53 11 15 6 *
    - cron: 53 11 16 6 *
    - cron: 53 11 17 6 *
    - cron: 54 11 18 6 *
    - cron: 54 11 19 6 *
    - cron: 54 11 20 6 *
    - cron: 54 11 21 6 *
    - cron: 55 11 22 6 *
    - cron: 55 11 23 6 *
    - cron: 55 11 24 6 *
    - cron: 55 11 25 6 *
    - cron: 55 11 26 6 *
    - cron: 56 11 27 6 *
    - cron: 56 11 28 6 *
    - cron: 56 11 29 6 *
    - cron: 56 11 30 6 *
jobs:
  reminder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Send reminder to slack
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "@here Bentar lagi sholat ISYA loh! :mosque:"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
