name: SHUBUH reminder
on:
  schedule:
    - cron: 26 21 31 5 *
    - cron: 26 21 1 6 *
    - cron: 27 21 2 6 *
    - cron: 27 21 3 6 *
    - cron: 27 21 4 6 *
    - cron: 27 21 5 6 *
    - cron: 27 21 6 6 *
    - cron: 27 21 7 6 *
    - cron: 28 21 8 6 *
    - cron: 28 21 9 6 *
    - cron: 28 21 10 6 *
    - cron: 28 21 11 6 *
    - cron: 28 21 12 6 *
    - cron: 29 21 13 6 *
    - cron: 29 21 14 6 *
    - cron: 29 21 15 6 *
    - cron: 29 21 16 6 *
    - cron: 29 21 17 6 *
    - cron: 30 21 18 6 *
    - cron: 30 21 19 6 *
    - cron: 30 21 20 6 *
    - cron: 30 21 21 6 *
    - cron: 30 21 22 6 *
    - cron: 31 21 23 6 *
    - cron: 31 21 24 6 *
    - cron: 31 21 25 6 *
    - cron: 31 21 26 6 *
    - cron: 32 21 27 6 *
    - cron: 32 21 28 6 *
    - cron: 32 21 29 6 *
jobs:
  reminder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Send reminder to slack
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "@here Bentar lagi sholat SHUBUH loh! :mosque:"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
