name: ISYA reminder
on:
  schedule:
    - cron: 55 11 1 6 *
    - cron: 55 11 2 6 *
    - cron: 56 11 3 6 *
    - cron: 56 11 4 6 *
    - cron: 56 11 5 6 *
    - cron: 56 11 6 6 *
    - cron: 56 11 7 6 *
    - cron: 57 11 8 6 *
    - cron: 57 11 9 6 *
    - cron: 57 11 10 6 *
    - cron: 57 11 11 6 *
    - cron: 57 11 12 6 *
    - cron: 58 11 13 6 *
    - cron: 58 11 14 6 *
    - cron: 58 11 15 6 *
    - cron: 58 11 16 6 *
    - cron: 58 11 17 6 *
    - cron: 59 11 18 6 *
    - cron: 59 11 19 6 *
    - cron: 59 11 20 6 *
    - cron: 59 11 21 6 *
    - cron: 0 12 22 6 *
    - cron: 0 12 23 6 *
    - cron: 0 12 24 6 *
    - cron: 0 12 25 6 *
    - cron: 0 12 26 6 *
    - cron: 1 12 27 6 *
    - cron: 1 12 28 6 *
    - cron: 1 12 29 6 *
    - cron: 1 12 30 6 *
env:
  SCHEDULE_NAME: ISYA
jobs:
  reminder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Send reminder to slack
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "@here Bentar lagi sholat ${SCHEDULE_NAME} loh! :mosque:"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
