name: MAGRIB reminder
on:
  schedule:
    - cron: 36 10 1 6 *
    - cron: 36 10 2 6 *
    - cron: 36 10 3 6 *
    - cron: 36 10 4 6 *
    - cron: 36 10 5 6 *
    - cron: 37 10 6 6 *
    - cron: 37 10 7 6 *
    - cron: 37 10 8 6 *
    - cron: 37 10 9 6 *
    - cron: 37 10 10 6 *
    - cron: 37 10 11 6 *
    - cron: 38 10 12 6 *
    - cron: 38 10 13 6 *
    - cron: 38 10 14 6 *
    - cron: 38 10 15 6 *
    - cron: 38 10 16 6 *
    - cron: 38 10 17 6 *
    - cron: 39 10 18 6 *
    - cron: 39 10 19 6 *
    - cron: 39 10 20 6 *
    - cron: 39 10 21 6 *
    - cron: 40 10 22 6 *
    - cron: 40 10 23 6 *
    - cron: 40 10 24 6 *
    - cron: 40 10 25 6 *
    - cron: 40 10 26 6 *
    - cron: 41 10 27 6 *
    - cron: 41 10 28 6 *
    - cron: 41 10 29 6 *
    - cron: 41 10 30 6 *
jobs:
  reminder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Send reminder to slack
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "@here Bentar lagi sholat MAGRIB loh! :mosque:"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
