name: DZUHUR reminder
on:
  schedule:
    - cron: 48 4 1 6 *
    - cron: 48 4 2 6 *
    - cron: 48 4 3 6 *
    - cron: 48 4 4 6 *
    - cron: 48 4 5 6 *
    - cron: 48 4 6 6 *
    - cron: 49 4 7 6 *
    - cron: 49 4 8 6 *
    - cron: 49 4 9 6 *
    - cron: 49 4 10 6 *
    - cron: 49 4 11 6 *
    - cron: 50 4 12 6 *
    - cron: 50 4 13 6 *
    - cron: 50 4 14 6 *
    - cron: 50 4 15 6 *
    - cron: 50 4 16 6 *
    - cron: 51 4 17 6 *
    - cron: 51 4 18 6 *
    - cron: 51 4 19 6 *
    - cron: 51 4 20 6 *
    - cron: 52 4 21 6 *
    - cron: 52 4 22 6 *
    - cron: 52 4 23 6 *
    - cron: 52 4 24 6 *
    - cron: 52 4 25 6 *
    - cron: 53 4 26 6 *
    - cron: 53 4 27 6 *
    - cron: 53 4 28 6 *
    - cron: 53 4 29 6 *
    - cron: 53 4 30 6 *
env:
  SCHEDULE_NAME: DZUHUR
jobs:
  reminder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Send reminder to slack
        run: echo "Sending $SCHEDULE_NAME reminder to slack"
