name: ASHR reminder
on:
  schedule:
    - cron: 5 8 1 6 *
    - cron: 5 8 2 6 *
    - cron: 5 8 3 6 *
    - cron: 5 8 4 6 *
    - cron: 5 8 5 6 *
    - cron: 5 8 6 6 *
    - cron: 6 8 7 6 *
    - cron: 6 8 8 6 *
    - cron: 6 8 9 6 *
    - cron: 6 8 10 6 *
    - cron: 6 8 11 6 *
    - cron: 7 8 12 6 *
    - cron: 7 8 13 6 *
    - cron: 7 8 14 6 *
    - cron: 7 8 15 6 *
    - cron: 7 8 16 6 *
    - cron: 8 8 17 6 *
    - cron: 8 8 18 6 *
    - cron: 8 8 19 6 *
    - cron: 8 8 20 6 *
    - cron: 8 8 21 6 *
    - cron: 9 8 22 6 *
    - cron: 9 8 23 6 *
    - cron: 9 8 24 6 *
    - cron: 9 8 25 6 *
    - cron: 10 8 26 6 *
    - cron: 10 8 27 6 *
    - cron: 10 8 28 6 *
    - cron: 10 8 29 6 *
    - cron: 10 8 30 6 *
jobs:
  reminder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Send reminder to slack
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "@here Bentar lagi sholat ASHR loh! :mosque:"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
