name: DZUHUR reminder
on:
  schedule:
    - cron: 43 4 1 6 *
    - cron: 43 4 2 6 *
    - cron: 43 4 3 6 *
    - cron: 43 4 4 6 *
    - cron: 43 4 5 6 *
    - cron: 43 4 6 6 *
    - cron: 44 4 7 6 *
    - cron: 44 4 8 6 *
    - cron: 44 4 9 6 *
    - cron: 44 4 10 6 *
    - cron: 44 4 11 6 *
    - cron: 45 4 12 6 *
    - cron: 45 4 13 6 *
    - cron: 45 4 14 6 *
    - cron: 45 4 15 6 *
    - cron: 45 4 16 6 *
    - cron: 46 4 17 6 *
    - cron: 46 4 18 6 *
    - cron: 46 4 19 6 *
    - cron: 46 4 20 6 *
    - cron: 47 4 21 6 *
    - cron: 47 4 22 6 *
    - cron: 47 4 23 6 *
    - cron: 47 4 24 6 *
    - cron: 47 4 25 6 *
    - cron: 48 4 26 6 *
    - cron: 48 4 27 6 *
    - cron: 48 4 28 6 *
    - cron: 48 4 29 6 *
    - cron: 48 4 30 6 *
jobs:
  reminder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Send reminder to slack
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "@here Bentar lagi sholat DZUHUR loh! :mosque:"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
