name: MAGRIB reminder
on:
  schedule:
    - cron: 41 10 1 6 *
    - cron: 41 10 2 6 *
    - cron: 41 10 3 6 *
    - cron: 41 10 4 6 *
    - cron: 41 10 5 6 *
    - cron: 42 10 6 6 *
    - cron: 42 10 7 6 *
    - cron: 42 10 8 6 *
    - cron: 42 10 9 6 *
    - cron: 42 10 10 6 *
    - cron: 42 10 11 6 *
    - cron: 43 10 12 6 *
    - cron: 43 10 13 6 *
    - cron: 43 10 14 6 *
    - cron: 43 10 15 6 *
    - cron: 43 10 16 6 *
    - cron: 43 10 17 6 *
    - cron: 44 10 18 6 *
    - cron: 44 10 19 6 *
    - cron: 44 10 20 6 *
    - cron: 44 10 21 6 *
    - cron: 45 10 22 6 *
    - cron: 45 10 23 6 *
    - cron: 45 10 24 6 *
    - cron: 45 10 25 6 *
    - cron: 45 10 26 6 *
    - cron: 46 10 27 6 *
    - cron: 46 10 28 6 *
    - cron: 46 10 29 6 *
    - cron: 46 10 30 6 *
env:
  SCHEDULE_NAME: MAGRIB
jobs:
  reminder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Send reminder to slack
        run: echo "Sending $SCHEDULE_NAME reminder to slack"
